.PHONY: fmt
fmt:
	@go vet ./...
	@go fmt ./...
	@staticcheck ./...

.PHONY: test
test:
	@go test --race --cover ./...

.PHONY: bench
bench:
	@go test --cover --bench=. ./...

.PHONY: fuzz
fuzz:
	@echo "Please use fuzz-fast for a quick test or fuzz-slow if you have an hour or more"

.PHONY: fuzz-fast
fuzz-fast:
	@echo "[🧪] Fuzzing... (1/4)"
	@go test --fuzztime 45s --fuzz "FuzzHelpers" ./...
	@echo "[🧪] Fuzzing... (2/4)"
	@go test --fuzztime 45s --fuzz "FuzzUtils" ./...
	@echo "[🧪] Fuzzing... (3/4)"
	@go test --fuzztime 50s --fuzz "FuzzAdd" ./...
	@echo "[🧪] Fuzzing... (4/4)"
	@go test --fuzztime 60s --fuzz "FuzzParseString" ./...

.PHONY: fuzz-slow
fuzz-slow:
	@echo "[🧪] Fuzzing... (1/4)"
	@go test --fuzztime 15m --fuzz "FuzzHelpers" ./...
	@echo "[🧪] Fuzzing... (2/4)"
	@go test --fuzztime 15m --fuzz "FuzzUtils" ./...
	@echo "[🧪] Fuzzing... (3/4)"
	@go test --fuzztime 20m --fuzz "FuzzAdd" ./...
	@echo "[🧪] Fuzzing... (4/4)"
	@go test --fuzztime 25m --fuzz "FuzzParseString" ./...

.PHONY: full-test
full-test:
	@echo "[🧪] This test will run a couple of hours, please take a break."
	@echo "[🧪] Formatting..."
	@go vet
	@go fmt
	@echo "[🧪] Testing... (1/2)"
	go test --race --cover ./...
	@echo "[🧪] Testing... (2/2)"
	go test --race --cover --bench=. ./...
	@echo "[🧪] Fuzzing... (1/4)"
	go test --fuzztime 25m --fuzz "FuzzHelpers" ./...
	@echo "[🧪] Fuzzing... (2/4)"
	go test --fuzztime 25m --fuzz "FuzzUtils" ./...
	@echo "[🧪] Fuzzing... (3/4)"
	go test --fuzztime 35m --fuzz "FuzzAdd" ./...
	@echo "[🧪] Fuzzing... (4/4)"
	go test --fuzztime 40m --fuzz "FuzzParseString" ./...
